name: Pet Store Pet Service CI/CD to Azure App Service with image from Dockerhub

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

on:
  push:
    branches:
      - main
    paths:
      - petstore/petstorepetservice/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checking the file system listing for Pet Store Pet Service
      run: |
        ls -al
    - name: Update the version.json
      run: echo -n -e "{\"version\":\"$\",\"date\":\"$(date '+%m-%d-%Y %H:%M:%S')\"}" > petstore/petstorepetservice/src/main/resources/static/content/version.json
    - run: cat petstore/petstorepetservice/src/main/resources/static/content/version.json
    - uses: actions/setup-java@v2
      name: Building Pet Service with Java 13
      with:
        java-version: '13'
        distribution: 'adopt'
    - name: Run Maven build
      run: mvn -f petstore/petstorepetservice/pom.xml --batch-mode --update-snapshots verify
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: petstore/petstorepetservice/target/petstorepetservice-0.0.1-SNAPSHOT.jar
    - uses: actions/checkout@v2
    - name: Docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the docker image for apple silicon
      run: docker build -t petstorepetservice petstore/petstorepetservice -t $DOCKER_USER/images:petstorepetservice
    - name: Docker push apple silicon image
      run: docker push $DOCKER_USER/images:petstorepetservice
    - name: Build the docker image for x86
      run: docker buildx build --platform linux/amd64 -t petstorepetservicelinux petstore/petstorepetservice -t $DOCKER_USER/images:petstorepetservicelinux
    - name: Docker push x64 image
      run: docker push $DOCKER_USER/images:petstorepetservicelinux
